export const UPDATE_LOGIN_STATUS = 'UPDATE_LOGIN_STATUS';
export const SET_PAGE = 'SET_PAGE';
export const DISPLAY_LOGIN_FORM = 'DISPLAY_LOGIN_FORM';

export const OPEN_SIDENAV = 'OPEN_SIDENAV';
export const OPEN_SEARCH_BAR = 'OPEN_SEARCH_BAR';

export const SET_LOADING_STATUS = 'SET_LOADING_STATUS';
export const SET_ERROR_MESSAGE = 'SET_ERROR_MESSAGE';
